name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print_Greeting
        run: echo "Hello, we have started"
      - name: Print_more
        run: echo "Let's get this done."
    
