name: Test_NPM
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  npm1:
    runs-on: ubuntu-latest
    steps:
      - name: Copying Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: npm1
    runs-on: ubuntu-latest
    steps:
      - name: Copying Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Deploy Message
        run: echo "Deploying the project......."

      
    
