name: Test_NPM
on: push
jobs:
  npm1:
    runs-on: ubuntu-latest
    steps:
      - name: Copying Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      
    
